-- 20260423000000_campaign_rank_v1.sql
-- Subject/level/topic-specific rank tracking for Campaign mode.

begin;

create table if not exists public.campaign_rank_points (
  id bigint generated by default as identity primary key,
  player_id uuid not null references public.players(id) on delete cascade,
  subject text not null,
  level text not null,
  topic_kind text not null,
  topic_key text not null,
  topic_label text not null,
  rank_points int not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint campaign_rank_points_scope_unique unique (player_id, subject, level, topic_kind, topic_key),
  constraint campaign_rank_points_subject_check check (subject in ('math', 'physics', 'chemistry')),
  constraint campaign_rank_points_level_check check (level in ('A1', 'A2')),
  constraint campaign_rank_points_topic_kind_check check (topic_kind in ('chapter', 'topicTag')),
  constraint campaign_rank_points_rank_points_check check (rank_points >= 0 and rank_points <= 2000)
);

create index if not exists idx_campaign_rank_points_player_scope
  on public.campaign_rank_points(player_id, subject, level, topic_kind, topic_key);

alter table public.campaign_rank_points enable row level security;

drop policy if exists campaign_rank_points_select_own on public.campaign_rank_points;
create policy campaign_rank_points_select_own
  on public.campaign_rank_points for select
  to authenticated
  using (player_id = auth.uid());

create table if not exists public.campaign_rank_points_history (
  id bigint generated by default as identity primary key,
  player_id uuid not null references public.players(id) on delete cascade,
  subject text not null,
  level text not null,
  topic_kind text not null,
  topic_key text not null,
  topic_label text not null,
  old_points int not null,
  new_points int not null,
  delta int not null,
  outcome text not null,
  accuracy_pct int not null,
  correct_parts int not null,
  total_parts int not null,
  created_at timestamptz not null default now(),
  constraint campaign_rank_points_history_subject_check check (subject in ('math', 'physics', 'chemistry')),
  constraint campaign_rank_points_history_level_check check (level in ('A1', 'A2')),
  constraint campaign_rank_points_history_topic_kind_check check (topic_kind in ('chapter', 'topicTag')),
  constraint campaign_rank_points_history_accuracy_check check (accuracy_pct >= 0 and accuracy_pct <= 100),
  constraint campaign_rank_points_history_outcome_check check (outcome in ('win', 'loss'))
);

create index if not exists idx_campaign_rank_points_history_player_created
  on public.campaign_rank_points_history(player_id, created_at desc);

alter table public.campaign_rank_points_history enable row level security;

drop policy if exists campaign_rank_points_history_select_own on public.campaign_rank_points_history;
create policy campaign_rank_points_history_select_own
  on public.campaign_rank_points_history for select
  to authenticated
  using (player_id = auth.uid());

create or replace function public.update_campaign_rank_points_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists update_campaign_rank_points_updated_at on public.campaign_rank_points;
create trigger update_campaign_rank_points_updated_at
  before update on public.campaign_rank_points
  for each row execute function public.update_campaign_rank_points_updated_at();

create or replace function public.record_campaign_challenge_v1(
  p_player_id uuid,
  p_subject text,
  p_level text,
  p_topic_kind text,
  p_topic_key text,
  p_topic_label text,
  p_correct_parts int,
  p_total_parts int
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_accuracy_pct int;
  v_outcome text;
  v_old_points int;
  v_delta int;
  v_new_points int;
  v_required_pct int := 65;
begin
  if p_total_parts <= 0 then
    raise exception 'total_parts must be > 0';
  end if;

  if p_subject not in ('math', 'physics', 'chemistry') then
    raise exception 'invalid subject %', p_subject;
  end if;

  if p_level not in ('A1', 'A2') then
    raise exception 'invalid level %', p_level;
  end if;

  if p_topic_kind not in ('chapter', 'topicTag') then
    raise exception 'invalid topic_kind %', p_topic_kind;
  end if;

  if length(trim(coalesce(p_topic_key, ''))) = 0 then
    raise exception 'topic_key is required';
  end if;

  if length(trim(coalesce(p_topic_label, ''))) = 0 then
    raise exception 'topic_label is required';
  end if;

  perform 1
    from public.players
   where id = p_player_id
   for update;

  if not found then
    raise exception 'player not found';
  end if;

  v_accuracy_pct := floor(p_correct_parts::numeric / p_total_parts * 100);
  v_accuracy_pct := public._clamp_int(v_accuracy_pct, 0, 100);

  if v_accuracy_pct >= v_required_pct then
    v_outcome := 'win';
    v_delta := 10;
  else
    v_outcome := 'loss';
    v_delta := -10;
  end if;

  insert into public.campaign_rank_points (
    player_id,
    subject,
    level,
    topic_kind,
    topic_key,
    topic_label,
    rank_points
  ) values (
    p_player_id,
    p_subject,
    p_level,
    p_topic_kind,
    trim(p_topic_key),
    trim(p_topic_label),
    0
  )
  on conflict (player_id, subject, level, topic_kind, topic_key)
  do update set
    topic_label = excluded.topic_label
  returning rank_points into v_old_points;

  v_new_points := public._clamp_int(v_old_points + v_delta, 0, 2000);

  update public.campaign_rank_points
     set rank_points = v_new_points,
         topic_label = trim(p_topic_label),
         updated_at = now()
   where player_id = p_player_id
     and subject = p_subject
     and level = p_level
     and topic_kind = p_topic_kind
     and topic_key = trim(p_topic_key);

  insert into public.campaign_rank_points_history (
    player_id,
    subject,
    level,
    topic_kind,
    topic_key,
    topic_label,
    old_points,
    new_points,
    delta,
    outcome,
    accuracy_pct,
    correct_parts,
    total_parts
  ) values (
    p_player_id,
    p_subject,
    p_level,
    p_topic_kind,
    trim(p_topic_key),
    trim(p_topic_label),
    v_old_points,
    v_new_points,
    v_new_points - v_old_points,
    v_outcome,
    v_accuracy_pct,
    p_correct_parts,
    p_total_parts
  );

  return jsonb_build_object(
    'outcome', v_outcome,
    'accuracy_pct', v_accuracy_pct,
    'old_points', v_old_points,
    'new_points', v_new_points,
    'delta', v_new_points - v_old_points,
    'topic_kind', p_topic_kind,
    'topic_key', trim(p_topic_key),
    'topic_label', trim(p_topic_label)
  );
end;
$$;

grant execute on function public.record_campaign_challenge_v1(
  uuid,
  text,
  text,
  text,
  text,
  text,
  int,
  int
) to authenticated;

commit;
