// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pislbnqydxwxxdaambcq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBpc2xibnF5ZHh3eHhkYWFtYmNxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY0Mzk0NjcsImV4cCI6MjA3MjAxNTQ2N30.YiwE4rjtzMEfUR8phAEiq6zeQVUwPRbxOr4ufRxWpdM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});